// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4jDtie9KKGZ7XzOfAdfoxWMH4-3Fimbk',
    appId: '1:189041618462:web:4ad050e79f38e7e07bc80f',
    messagingSenderId: '189041618462',
    projectId: 'astro-app1',
    authDomain: 'astro-app1.firebaseapp.com',
    storageBucket: 'astro-app1.appspot.com',
    measurementId: 'G-M1QF8HEYNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNeryjLopXXQzjuqDJU6YpUr_PjY4FfDs',
    appId: '1:189041618462:android:37ae6bf02812a3b37bc80f',
    messagingSenderId: '189041618462',
    projectId: 'astro-app1',
    storageBucket: 'astro-app1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1wfLFEN8N5FlranMwjLwmXVieWROsKRc',
    appId: '1:189041618462:ios:ada57125336e8c107bc80f',
    messagingSenderId: '189041618462',
    projectId: 'astro-app1',
    storageBucket: 'astro-app1.appspot.com',
    iosBundleId: 'com.example.comet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1wfLFEN8N5FlranMwjLwmXVieWROsKRc',
    appId: '1:189041618462:ios:ada57125336e8c107bc80f',
    messagingSenderId: '189041618462',
    projectId: 'astro-app1',
    storageBucket: 'astro-app1.appspot.com',
    iosBundleId: 'com.example.comet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4jDtie9KKGZ7XzOfAdfoxWMH4-3Fimbk',
    appId: '1:189041618462:web:79f19a324c8fc65d7bc80f',
    messagingSenderId: '189041618462',
    projectId: 'astro-app1',
    authDomain: 'astro-app1.firebaseapp.com',
    storageBucket: 'astro-app1.appspot.com',
    measurementId: 'G-LR1TDRJ4W0',
  );
}
